FROM python:3.14-slim

RUN pip install --no-cache-dir uv

WORKDIR /app

COPY pyproject.toml uv.lock README.md ./
COPY src ./src
COPY migrations ./migrations

RUN uv sync --frozen

CMD ["uv", "run", "taskiq", "worker", "algorunner.worker.tasks:broker", "--workers", "1"]
